### ISSUE TITLE
Request for Access to Annotated Data Mentioned in the Paper

### ISSUE THREAD

**Issue by CommodoreEU** [gseetha04/LLMs-Medicaldata#1]
Dear Authors,

I recently came across your paper, "Causality Extraction from Medical Text Using Large Language Models (LLMs)", and found it highly interesting. In the paper, it is mentioned that both the annotated data and the code would be publicly available in this repository. However, after reviewing the repository, I was unable to locate the annotated data.

Could you kindly clarify if the annotated data is available elsewhere or, if not, consider uploading it to the repository?

Thank you for your time, and I look forward to your response.

**Comment by gseetha04** [comment]
Here is the link to the annotated data https://github.com/gseetha04/Gestational-diabetes-annotated

**Comment by CommodoreEU** [comment]
Thank you for your prompt response and for sharing the link to the annotated data; much appreciated.
